language: scala
sudo: required
dist: trusty
scala:
- 2.11.12
- 2.13.1
notifications:
  slack:
  - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
  - dev@websudos.co.uk
jdk:
- oraclejdk9
branches:
  only:
  - master
  - develop
matrix:
  include:
  - scala: 2.12.8
    jdk: oraclejdk9
    env: RUN_WITH_COVERAGE=true PUBLISH_ARTIFACT=true
env:
  global:
  - RUN_WITH_COVERAGE: false
  - PUBLISH_ARTIFACT: false
  - TARGET_SCALA_VERSION: 2.12.8
  - GH_REF: github.com/outworkers/util.git
  - secure: Onl6jQhDgCHVhsxIhC2FltwTlvTWI5815lI9wsb79OvE+Xl/hh8XcafOBzUJ/LtKmt021oieOsR53RAdIJDKhNrKo3AQYoyp3rAX48zCInE0Y29slKVCwj51w5Mns+aYlPbJcHJvRNWkFIpaQ1AmBvkHfc0A0rxfoSB1lOIrtHs=
  - secure: k/DGy5KkvzmQNJEfazsEoD6biwkIoYC9DyjhDTMCxhXLz/mURsCtfhdWo3Uz4nhuX3qDK0N/6C6BTwl0ktVEA7eH8XZQY/dW1lLTY3jglD2U/FhAfCngbcI+ToL5kdK77Zy4LKvu4XBKXfSusI20E1gbK+Tjp1uCkNvVaAyyVv0=
  - secure: Mq2DExZRRQBvLwcw8O+tNTbT7M0NzWEGid30PnlAKtXQlupAo45VBoSb7fEY9zWqLaH7fJEQ/AauirgLdPPwqhVT1qx91ioSZ3+ikzSdkZu5LbfM89C1rnvpjpWY3uiCwtAYql2yIu3lhWncpIXl2rBhwSHi6DUTnRUnjzd/yws=
  - secure: KJca+iYGyO9svC+V1UF5y7Ff9OtS83CRY6VHZ0cKtBi6xID68J9BE/70TyDgNM6eLdweVw3Qw2tVUJdlFlkq9x4swOJqZkG7CodO9+NsHcYvlOWVNEXJ8ETu6vli5BY3w4UJlebjszUjOmC4cW7h5Y+omW0NHT6RrYbxVmvkQgs=
  - secure: McqtU8mq/QFlG2s2lfeKyNbCPU1IPGNF4FQFyYsWU94TMhUh7KGBDQFvdxxabDngwPWuMKvA59PFCqzbvmJr9qug4pYEAJaAAkfCQVUhU6fczdrH1k9mAdERIBvB1T6zWXCpIW1NTWkpq8Ew2aLGTpCJ4KShjGS0uzDgRyXjC+Y=
  - secure: lPvdpbnKHSdkeIfh5pT2e3H3uR6kh11Wlf1YWgbvkC3eZrWeRmwKGFwMrPKP1gu7Y4+I563a0vR2Zgli+xGCibS6JY/NHUx3B8j8CzvsMfSEoG6vOpNE2uCM3EbugJRGMausjQkqIH6gmqQaHLgTVtj2JnkqWOM25EVvgqL7Ew8=
  - secure: KN/A3hwoeMzamO07Lgd5nPUNrA2+o0rq1e+F+OhiG9FuwLvUZvhCVa5Bx5YbtXGKPPhvgdWQBexRvi3fQF3BxvIkRvDuf9SUElGBVvzJlsOuJOVV6TezjZigZbLGMXkOZmG3qdG3g6k6Fxd5KPH1wb8MwDgGNMu3V4IEcVis5n8=
  - secure: MI5pHnXQE9vSZvjohlf8rs/39NY9FynBWk95h/xKHWdGkX+kNwJmd59I5IzjNPZ0vNu6nnIE9ciX6MuKCQZFe1IJyaJ2J2VCUCeAyaX3m1k8uXm9Nj9HY+I6ZXzieMqhyneVzG7efsHQqmitOHFfIMoiKDFxBLjiGWXwjl4dCto=
  - secure: H3EdkGmh7G1fWwJPK0lO9u2o6HBj8WvyN4wKzkEg4wWXBEYRcGaSF1YOCh3roXjo6CAUgRN30E4NHXVq4x8wnhahLu/KiHR3uOAY5xj0A404MhWPxOvhjq5okd+B/DNFB4q0BqupAqHbzutIx8AnDUjHg/I8KeIl6oM87rteSgc=
cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.nvm"
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
before_script: travis_retry sbt "++ $TRAVIS_SCALA_VERSION update"
script: "./build/run_tests.sh"
after_success:
- "./build/publish_develop.sh"
